FROM amazoncorretto:8

# Update the system and install necessary packages
RUN yum -y update
RUN yum -y install yum-utils
RUN yum -y groupinstall development

# Install Python 3 and related packages
RUN yum list python3*
RUN yum -y install python3 python3-dev python3-pip python3-virtualenv

# Verify Python installation
RUN python -V
RUN python3 -V

# Set environment variables for PySpark
ENV PYSPARK_DRIVER_PYTHON python3
ENV PYSPARK_PYTHON python3

# Upgrade pip to the latest version
RUN pip3 install --upgrade pip

# Install necessary Python libraries
RUN pip3 install "apache_beam[aws]==2.61.0"
#2.48
RUN pip3 install tensorflow==2.18.0

# Verify the installation of Apache Beam and TensorFlow
RUN python3 -c "import apache_beam; import tensorflow as tf; print('Apache Beam version:', apache_beam.__version__); print('TensorFlow version:', tf.__version__)"

